const assert = require('assert');
const express = require('express');
const { pool } = require('../db/connection');
const { loadAccountData, loadAccountSummary, saveAccountData } = require('../db/accounts');
const { loadCashState } = require('../services/accountCash');
const { addCashFlow, deleteCashFlow, recomputeCash } = require('../services/tradeLedger');
const router = require('../routes/accounts');
const U='cash_income_contract_test', A='现金收益回归', ID='cash_income_contract_test_id';
const tables=['positions','trades','nav_history','cash_flows','nav_position_snapshots','account_data','accounts'];
async function cleanup() {
  await pool.query("DELETE FROM fundamental.corporate_actions WHERE source_key LIKE 'cash_preserve_test_%'");
  for(const t of tables) await pool.query(`DELETE FROM ${t} WHERE username=$1`,[U]);
  await pool.query('DELETE FROM users WHERE username=$1',[U]);
}
(async()=>{
  let server,hkCoverageScope,hkCoverageBackup;
  try {
    await cleanup();
    await pool.query("INSERT INTO users(username,password,accounts,status,auth_version) VALUES($1,'x',$2,'active',1)",[U,JSON.stringify([A])]);
    await pool.query("INSERT INTO accounts(id,username,account_name,cash_base,hk_rate) VALUES($1,$2,$3,100,1)",[ID,U,A]);
    await pool.query("INSERT INTO account_data(username,account_name,data,version) VALUES($1,$2,'{}',0)",[U,A]);
    await pool.query(`INSERT INTO nav_history(username,account_name,account_id,date,nav,total_asset,invested,cash_cny,
      market_value_cny,system_market_value_at_snapshot,snapshot_source,is_locked,source_priority)
      VALUES($1,$2,$3,'2026-09-01',1,1000,1000,1000,0,0,'imported',true,100)`,[U,A,ID]);
    await pool.query(`INSERT INTO cash_flows(id,username,account_name,account_id,date,amount,origin,flow_type,status,event_key,anchor_date)
      VALUES('system',$1,$2,$3,'2026-09-02',3,'system','repo_interest','estimated','repo:2026-09-01','2026-09-01'),
      ('imported',$1,$2,$3,'2026-09-02',10,'imported','external_transfer','confirmed',NULL,NULL)`,[U,A,ID]);
    const d = await loadAccountData(U,A), s=await loadAccountSummary(U,A);
    assert.strictEqual(d.cash,1013); assert.strictEqual(s.cash,d.cash);
    assert.strictEqual(d.authoritativeInvested,1010);
    assert.strictEqual(d.cashConfirmed,1010); assert.strictEqual(s.cashEstimatedDelta,3);
    assert.strictEqual(await recomputeCash(pool,U,A),1013);
    assert.strictEqual((await loadCashState(U,A,pool,'2026-08-31')).value,100);
    assert.strictEqual((await loadCashState(U,A,pool,'2026-09-01')).value,1000);
    assert.strictEqual(d.cashFlows[0].date,'2026-09-02','PG DATE必须在SQL边界序列化为文本');
    assert.strictEqual((await pool.query("SELECT data_type FROM information_schema.columns WHERE table_name='cash_flows' AND column_name='date'")).rows[0].data_type,'date');
    // 旧页面未带自动行，与完整响应回传两个分支。
    await saveAccountData(U,A,{cashBase:100,cashFlows:[]},0,null,['cashFlows']);
    assert.strictEqual((await loadAccountData(U,A)).cash,1013);
    let current=await loadAccountData(U,A);
    await saveAccountData(U,A,{...current,cashFlows:current.cashFlows.map(f=>({...f,amount:999}))},current.version,null,['cashFlows']);
    assert.strictEqual((await loadAccountData(U,A)).cash,1013);
    current=await loadAccountData(U,A);
    await assert.rejects(()=>saveAccountData(U,A,{...current,cashFlows:[{id:'system',date:'2026-09-02',amount:999}]},current.version,null,['cashFlows']),/不能.*流水/);
    await assert.rejects(()=>saveAccountData(U,A,{...current,cashFlows:[{id:'fake',date:'2026-09-02',amount:999,origin:'system'}]},current.version,null,['cashFlows']),/伪造/);
    await assert.rejects(()=>deleteCashFlow(U,A,'system',current.version),/不存在/);
    await assert.rejects(()=>deleteCashFlow(U,A,'imported',current.version),/不存在/);
    await assert.rejects(()=>addCashFlow(U,A,{id:'system',date:'2026-09-02',amount:1},current.version),/不能覆盖/);
    await assert.rejects(()=>addCashFlow(U,A,{date:'2026-02-30',amount:1},current.version),/日期/);
    await assert.rejects(()=>addCashFlow(U,A,{date:'2026-09-02',amount:Infinity},current.version),/金额/);
    const add = await addCashFlow(U,A,{id:'manual',date:'2026-09-02',amount:20},current.version);
    assert.strictEqual(add.cash,1033);
    const retry=await addCashFlow(U,A,{id:'manual',date:'2026-09-02',amount:20},current.version);
    assert.strictEqual(retry.skipped,'duplicate');
    current=await loadAccountData(U,A);
    await deleteCashFlow(U,A,'manual',current.version);
    assert.strictEqual((await loadAccountData(U,A)).cash,1013);
    const app=express(); app.use(express.json());
    app.use((req,res,next)=>{req.session={user:U,authVersion:1};next();}); app.use('/api',router);
    server=await new Promise(resolve=>{const x=app.listen(0,'127.0.0.1',()=>resolve(x));});
    const base='http://127.0.0.1:'+server.address().port;
    const ok=await fetch(base+'/api/accounts/'+encodeURIComponent(A)+'/cash-income/coverage');
    assert.strictEqual(ok.status,200); assert.strictEqual((await ok.json()).cashAnchorDate,'2026-09-01');
    const denied=await fetch(base+'/api/accounts/'+encodeURIComponent('他人账户')+'/cash-income/coverage');
    assert.strictEqual(denied.status,403);
    await pool.query('DELETE FROM cash_flows WHERE username=$1 AND origin=\'system\'',[U]);
    const {settleCashIncome}=require('../services/cashIncome');
    const first=await settleCashIncome(U,A,{targetDate:'2026-09-04',enable:true});
    assert(first.changed>0);
    await require('../db/accounts').upsertNav(U,A,{date:'2026-09-03',nav:1.0001,totalAsset:1011,invested:1010});
    const saved=(await pool.query("SELECT diagnostics FROM nav_history WHERE username=$1 AND date='2026-09-03'",[U])).rows[0];
    assert.strictEqual(saved.diagnostics.cashIncomeVersion,'cash-income-v1');
    await settleCashIncome(U,A,{targetDate:'2026-09-04'});
    assert.strictEqual(Number((await pool.query("SELECT total_asset FROM nav_history WHERE username=$1 AND date='2026-09-03'",[U])).rows[0].total_asset),1011);
    const after=await loadAccountData(U,A);
    assert.strictEqual(after.authoritativeInvested,1010);
    const retryIncome=await settleCashIncome(U,A,{targetDate:'2026-09-04'});
    assert.strictEqual(retryIncome.changed,0);
    assert.strictEqual(retryIncome.navUpdated,0);
    assert.strictEqual((await loadAccountData(U,A)).cash,after.cash);
    await assert.rejects(()=>settleCashIncome(U,A,{targetDate:'2026-09-04',expectedVersion:0}),/已修改/);
    const active=(await pool.query("SELECT id FROM cash_flows WHERE username=$1 AND flow_type='repo_interest' ORDER BY date LIMIT 1",[U])).rows[0];
    await pool.query("UPDATE cash_flows SET status='confirmed',amount=1.23,amount_cny=1.23,quality_status='broker_settlement' WHERE username=$1 AND id=$2",[U,active.id]);
    await settleCashIncome(U,A,{targetDate:'2026-09-04'});
    assert.strictEqual(Number((await pool.query('SELECT amount FROM cash_flows WHERE username=$1 AND id=$2',[U,active.id])).rows[0].amount),1.23);
    assert.strictEqual((await pool.query('SELECT count(*)::int AS n FROM cash_flows WHERE username=$1 AND id=$2',[U,active.id])).rows[0].n,1);
    await pool.query(`INSERT INTO nav_history(username,account_name,account_id,date,nav,total_asset,invested,cash_cny,snapshot_source,is_locked,source_priority)
      VALUES($1,$2,$3,'2026-09-04',1,2000,1010,2000,'imported',true,100)`,[U,A,ID]);
    await settleCashIncome(U,A,{targetDate:'2026-09-04'});
    assert.strictEqual((await loadAccountData(U,A)).cash,2000);
    // 新官方版本缺净额不能抹掉同一事件的上一份有效估算；补齐后替换而非叠加。
    const instrument=(await pool.query("SELECT instrument_id,canonical_code FROM core.instruments WHERE market='CN' AND asset_class='stock' ORDER BY instrument_id LIMIT 1")).rows[0];
    assert(instrument,'隔离库须有标准证券身份');
    const code=instrument.canonical_code;
    await pool.query(`INSERT INTO positions(id,username,account_name,code,instrument_id,quantity,type,subtype) VALUES('cash_preserve_position',$1,$2,$3,$4,100,'股权','A股')`,[U,A,code,instrument.instrument_id]);
    await pool.query(`INSERT INTO trades(id,username,account_name,date,trade_date,direction,code,quantity,amount) VALUES('cash_preserve_trade',$1,$2,'2026-09-01','2026-09-01','open',$3,100,0)`,[U,A,code]);
    const source=(await pool.query('SELECT source_id FROM ops.data_sources ORDER BY source_id LIMIT 1')).rows[0].source_id;
    await pool.query(`INSERT INTO fundamental.corporate_actions(instrument_id,action_type,record_date,pay_date,status,cash_per_share_after_tax,source_id,source_key) VALUES($1,'dividend','2026-09-07','2026-09-08','实施',1,$2,'cash_preserve_test_old')`,[instrument.instrument_id,source]);
    await settleCashIncome(U,A,{targetDate:'2026-09-09'});
    const eventKey='dividend:'+instrument.instrument_id+':2026-09-07:2026-09-08';
    const amount=async()=>Number((await pool.query("SELECT amount FROM cash_flows WHERE username=$1 AND event_key=$2 AND status<>'revoked'",[U,eventKey])).rows[0]?.amount);
    assert.strictEqual(await amount(),100);
    await pool.query(`INSERT INTO fundamental.corporate_actions(instrument_id,action_type,record_date,pay_date,status,source_id,source_key,raw_payload) VALUES($1,'dividend','2026-09-07','2026-09-08','实施',$2,'cash_preserve_test_new','{"documentId":123}')`,[instrument.instrument_id,source]);
    const incomplete=await settleCashIncome(U,A,{targetDate:'2026-09-09'});assert(incomplete.pending.some(p=>p.eventKey===eventKey&&p.reason==='missing_net_amount'));
    assert.strictEqual(await amount(),100,'缺净额保留旧有效金额');
    await pool.query("UPDATE fundamental.corporate_actions SET cash_per_share_after_tax=0.9 WHERE source_key='cash_preserve_test_new'");
    await settleCashIncome(U,A,{targetDate:'2026-09-09'});assert.strictEqual(await amount(),90);
    assert.strictEqual((await settleCashIncome(U,A,{targetDate:'2026-09-09'})).changed,0);
    await pool.query(`UPDATE fundamental.corporate_actions SET cash_per_share_after_tax=NULL,cash_per_share_pre_tax=0.8,raw_payload='{"documentId":123,"taxTreatment":{"kind":"CN_personal_deferred_2015","sourceExcerpt":"自然人股东暂不扣缴个人所得税"}}' WHERE source_key='cash_preserve_test_new'`);
    await settleCashIncome(U,A,{targetDate:'2026-09-09'});assert.strictEqual(await amount(),80,'本事件明确递延政策允许按毛额发放初始股息，不预扣卖出税');
    await pool.query("UPDATE trades SET direction='buy' WHERE id='cash_preserve_trade' AND username=$1",[U]);
    await pool.query("INSERT INTO trades(id,username,account_name,date,trade_date,direction,code,quantity,amount) VALUES('cash_tax_sale',$1,$2,'2026-09-09','2026-09-09','sell',$3,50,0)",[U,A,code]);
    await pool.query('UPDATE positions SET quantity=50 WHERE username=$1 AND code=$2',[U,code]);
    const taxResult=await settleCashIncome(U,A,{targetDate:'2026-09-10'});
    assert.strictEqual(taxResult.deferredTaxCalculated,-8,'已授权公告/交易计算补税进入系统现金，不要求券商凭证');
    const taxFlow=(await pool.query("SELECT *,date::text FROM cash_flows WHERE username=$1 AND flow_type='dividend_tax' AND status='estimated'",[U])).rows[0];assert(taxFlow);assert.strictEqual(Number(taxFlow.amount),-8);assert.strictEqual(taxFlow.evidence.brokerVerified,false);
    assert.strictEqual((await settleCashIncome(U,A,{targetDate:'2026-09-10'})).changed,0);
    const version=(await loadAccountData(U,A)).version;
    await require('../services/cashIncomeActual').importActual(U,A,[{eventKey:taxFlow.event_key,date:'2026-09-10',flow_type:'dividend_tax',amountCny:'-7.50',sourceRef:'optional-actual-fixture'}],version);
    await settleCashIncome(U,A,{targetDate:'2026-09-10'});
    const replaced=(await pool.query("SELECT amount::text,status FROM cash_flows WHERE username=$1 AND event_key=$2 AND flow_type='dividend_tax'",[U,taxFlow.event_key])).rows;assert.strictEqual(replaced.length,1);assert.strictEqual(Number(replaced[0].amount),-7.5);assert.strictEqual(replaced[0].status,'confirmed');
    const hk=(await pool.query("SELECT instrument_id,canonical_code FROM core.instruments WHERE market='HK' AND asset_class='stock' ORDER BY instrument_id LIMIT 1")).rows[0];assert(hk);
    await pool.query("INSERT INTO positions(id,username,account_name,code,instrument_id,quantity,type,subtype) VALUES('cash_hk_position',$1,$2,$3,$4,100,'股权','港股')",[U,A,hk.canonical_code,hk.instrument_id]);
    await pool.query("INSERT INTO trades(id,username,account_name,date,trade_date,direction,code,quantity,amount) VALUES('cash_hk_buy',$1,$2,'2026-09-01','2026-09-01','buy',$3,100,0)",[U,A,hk.canonical_code]);
    for(const [suffix,perShare,nature] of [['normal','1','普通股息'],['special','0.1','特別股息']]){
      const raw={documentId:456,contentHash:'a'.repeat(64),period:'2026-06-30',dividendType:'中期',dividendNature:nature,taxTreatment:require('../services/cashDividendSettlement').parseHkTaxTreatment('股息所涉及的代扣所得稅不適用')};
      await pool.query("INSERT INTO fundamental.corporate_actions(instrument_id,action_type,record_date,pay_date,status,cash_per_share_pre_tax,currency_code,source_id,source_key,raw_payload) VALUES($1,'dividend','2026-09-07','2026-09-08','实施',$2,'CNY',$3,$4,$5)",[hk.instrument_id,perShare,source,'cash_preserve_test_hk_'+suffix,raw]);
    }
    const hkKey='dividend:'+hk.instrument_id+':2026-09-07:2026-09-08';
    const unknownChannel=await settleCashIncome(U,A,{targetDate:'2026-09-10'});assert(unknownChannel.pending.some(p=>p.eventKey===hkKey&&p.reason==='missing_stock_connect_channel'),'不把其他用户港股默认当港股通');
    await pool.query("UPDATE accounts SET cash_income_policy=cash_income_policy||'{\"stockConnectChannel\":\"stock_connect\"}'::jsonb WHERE id=$1",[ID]);
    await pool.query("INSERT INTO cash_flows(id,username,account_name,account_id,date,anchor_date,amount,flow_type,origin,status,event_key,calculation_version,quality_status,evidence) VALUES('legacy_hk_t0',$1,$2,$3,'2026-09-08','2026-09-04',88,'dividend','system','estimated',$4,'cash-income-v1','authorized_dividend_calculation','{\"authorizedPolicy\":\"cash-income-v1\"}')",[U,A,ID,hkKey]);
    const beforeHkReceipt=await settleCashIncome(U,A,{targetDate:'2026-09-10'});
    assert(beforeHkReceipt.upcomingDividends.some(r=>r.eventKey===hkKey&&r.receiptDate==='2026-09-11'));
    assert.strictEqual((await pool.query("SELECT count(*)::int AS n FROM cash_flows WHERE username=$1 AND event_key=$2 AND status='estimated'",[U,hkKey])).rows[0].n,0,'T+3之前不得计入可用现金');
    assert.strictEqual((await pool.query("SELECT status FROM cash_flows WHERE id='legacy_hk_t0'")).rows[0].status,'revoked','旧T+0估算撤销并保留修订');
    await settleCashIncome(U,A,{targetDate:'2026-09-11'});
    const hkRows=(await pool.query("SELECT amount::text,date::text,evidence FROM cash_flows WHERE username=$1 AND event_key=$2 AND flow_type='dividend'",[U,hkKey])).rows;
    assert.strictEqual(hkRows.length,1);assert.strictEqual(Number(hkRows[0].amount),88,'港股普通及特别公告股息无需券商流水即可计算入账');assert.strictEqual(hkRows[0].evidence.components.length,2);
    assert.strictEqual(hkRows[0].date,'2026-09-11');assert.strictEqual((await settleCashIncome(U,A,{targetDate:'2026-09-11'})).changed,0,'T+3重复重算幂等');
    hkCoverageScope='cash_dividend:'+hk.instrument_id;
    hkCoverageBackup=(await pool.query("SELECT * FROM ops.sync_cursors WHERE scope_key=$1 AND dataset_code='stock_cash_dividend_facts'",[hkCoverageScope])).rows[0];
    const coverage={fromDate:'2026-09-01',complete:true,parserVersion:require('../services/cashDividendFacts').PARSER};
    await pool.query("INSERT INTO account_cash_income_pending(account_id,pending_key,code,reason,state) VALUES($1,'coverage_with_action',$2,'missing_hk_dividend_facts','pending')",[ID,hk.canonical_code]);
    await pool.query("INSERT INTO ops.sync_cursors(instrument_id,scope_key,dataset_code,last_success_date,cursor_payload) VALUES($1,$2,'stock_cash_dividend_facts','2026-09-10',$3) ON CONFLICT(scope_key,dataset_code) DO UPDATE SET last_success_date=EXCLUDED.last_success_date,cursor_payload=EXCLUDED.cursor_payload",[hk.instrument_id,hkCoverageScope,coverage]);
    await settleCashIncome(U,A,{targetDate:'2026-09-11'});
    assert.strictEqual((await pool.query("SELECT state FROM account_cash_income_pending WHERE account_id=$1 AND pending_key='coverage_with_action'",[ID])).rows[0].state,'pending','旧日期覆盖不能关闭待办');
    await pool.query("UPDATE ops.sync_cursors SET last_success_date='2026-09-11' WHERE scope_key=$1 AND dataset_code='stock_cash_dividend_facts'",[hkCoverageScope]);
    await settleCashIncome(U,A,{targetDate:'2026-09-11'});
    assert.strictEqual((await pool.query("SELECT state FROM account_cash_income_pending WHERE account_id=$1 AND pending_key='coverage_with_action'",[ID])).rows[0].state,'resolved','有实施行动的证券仍按本作用域覆盖证据恢复');
    const hkVersion=(await loadAccountData(U,A)).version;
    await require('../services/cashIncomeActual').importActual(U,A,[{eventKey:hkKey,date:'2026-09-10',flow_type:'dividend',amountCny:'87',originalAmount:'87',currency:'CNY',sourceRef:'optional-hk-net-fixture',settlement:{amountBasis:'net'}}],hkVersion);
    await settleCashIncome(U,A,{targetDate:'2026-09-10'});assert.strictEqual(Number((await pool.query("SELECT amount FROM cash_flows WHERE username=$1 AND event_key=$2 AND flow_type='dividend'",[U,hkKey])).rows[0].amount),87,'实收只替换估算');
    await pool.query(`INSERT INTO cash_flows(id,username,account_name,date,amount,flow_type,origin,status) VALUES('cash_precision',$1,$2,'2026-09-10',0.000001,'external_transfer','manual','confirmed')`,[U,A]);
    const precise=await loadAccountData(U,A);assert.strictEqual(await recomputeCash(pool,U,A),precise.cash,'账本现金保留六位精度，与完整和摘要一致');assert.strictEqual((await loadAccountSummary(U,A)).cash,precise.cash);
    const detail=await fetch(base+'/api/accounts/'+encodeURIComponent(A)+'/cash-income');
    assert.strictEqual(detail.status,200);
    // 用户确认只影响本账户、本次事件和原资格股数；不改交易日期或官方公告。
    await pool.query("UPDATE fundamental.corporate_actions SET cash_per_share_pre_tax=1.2,cash_per_share_after_tax=NULL,currency_code='CNY',raw_payload='{\"documentId\":123}' WHERE source_key='cash_preserve_test_new'");
    const entitlement=require('../services/cashIncome').holdingAt((await pool.query('SELECT * FROM trades WHERE username=$1',[U])).rows,code,'2026-09-07',(await pool.query('SELECT * FROM positions WHERE username=$1',[U])).rows).quantity;
    const proof={eventKey,code,confirmedBy:U,holdingPeriod:'over_one_year',allEntitledShares:true,quantity:entitlement};
    await pool.query("UPDATE accounts SET cash_income_policy=cash_income_policy||$2::jsonb WHERE id=$1",[ID,JSON.stringify({cnDividendExemptions:[proof],dividendScopeExclusions:[{code:'404002',confirmedBy:U,outsideStockDividendScope:true,reason:'退市转债排除'}]})]);
    await pool.query("INSERT INTO trades(id,username,account_name,date,trade_date,direction,code,quantity,amount) VALUES('scope_exclusion',$1,$2,'2026-09-01','2026-09-01','open','404002',1,0)",[U,A]);
    await pool.query("INSERT INTO account_cash_income_pending(account_id,pending_key,code,reason,state) VALUES($1,'user_scope_exclusion','404002','missing_or_ambiguous_identity','pending')",[ID]);
    const exemptResult=await settleCashIncome(U,A,{targetDate:'2026-09-11'});
    assert(!exemptResult.pending.some(p=>p.eventKey===eventKey&&p.reason==='missing_net_amount'));
    const exemptFlow=(await pool.query("SELECT amount,evidence FROM cash_flows WHERE username=$1 AND event_key=$2 AND flow_type='dividend'",[U,eventKey])).rows[0];
    assert.strictEqual(Number(exemptFlow.amount),Math.round(entitlement*1.2*100)/100);
    assert.deepStrictEqual(exemptFlow.evidence.userTaxExemption,proof);
    assert.strictEqual((await pool.query("SELECT state FROM account_cash_income_pending WHERE account_id=$1 AND pending_key='user_scope_exclusion'",[ID])).rows[0].state,'excluded_by_user');
    assert.strictEqual((await settleCashIncome(U,A,{targetDate:'2026-09-11'})).changed,0);
    const {accountFingerprint}=require('../scripts/importCashIncomeEvidence');
    const immutableFingerprint=await accountFingerprint(U,A);
    await pool.query('UPDATE positions SET price=COALESCE(price,0)+0.01 WHERE username=$1',[U]);
    assert.strictEqual(await accountFingerprint(U,A),immutableFingerprint,'同步指纹检查股数/交易/锁定净值，不阻止生产行情正常更新');
    console.log('cash income DB: anchor consistency, DATE, source protection, retries and ownership passed');
  } finally { if(server) await new Promise(r=>server.close(r));if(hkCoverageScope){if(hkCoverageBackup)await pool.query("UPDATE ops.sync_cursors SET last_success_date=$2,cursor_payload=$3,last_attempt_at=$4,last_error=$5 WHERE scope_key=$1 AND dataset_code='stock_cash_dividend_facts'",[hkCoverageScope,hkCoverageBackup.last_success_date,hkCoverageBackup.cursor_payload,hkCoverageBackup.last_attempt_at,hkCoverageBackup.last_error]);else await pool.query("DELETE FROM ops.sync_cursors WHERE scope_key=$1 AND dataset_code='stock_cash_dividend_facts'",[hkCoverageScope]);} await cleanup(); await pool.end(); }
})().catch(e=>{console.error(e.stack);process.exitCode=1;});
