const assert=require('assert'),{parseHkTaxTreatment,estimateHkAnnouncement,hkReceiptDate}=require('../services/cashDividendSettlement');
const M=require('../../public/shared/nav-math');
const tax=parseHkTaxTreatment('股息所涉及的代扣所得稅\n不適用');assert(tax);assert.strictEqual(tax.layers[0].rate,'0.20');
assert(parseHkTaxTreatment('個人居民（中國內地登記地址）20%適用於內地個人投資者通過滬港通或深港通投資香港上市H股所得股息'));
assert.strictEqual(parseHkTaxTreatment('非居民企業10% H股個人股東10%'),null,'外國/企業投資者條款不套港股通個人');
const action=(id,amount,nature='普通股息')=>({action_id:id,pay_date:'2026-09-25',currency_code:'HKD',cash_per_share_pre_tax:amount,raw_payload:{documentId:id,contentHash:'a'.repeat(64),period:'2026-06-30',dividendType:'中期',dividendNature:nature,taxTreatment:tax}});
const fx=[{base_currency:'HKD',quote_currency:'CNY',rate_date:'2026-09-30',rate:'0.90',source_id:7},{base_currency:'HKD',quote_currency:'CNY',rate_date:'2026-10-01',rate:'1.1',source_id:7}];
const total=estimateHkAnnouncement({actions:[action(2,'0.056'),action(1,'0.056'),action(3,'0.008','特別股息')],quantity:10000,fxRows:fx,receiptDate:'2026-09-30'});
assert.strictEqual(total.amount,460.8,'普通+特别合计，旧版重复不叠加');assert.strictEqual(total.components.length,2);assert.strictEqual(total.components[0].fxDate,'2026-09-30');assert.strictEqual(total.brokerVerified,false);
assert.strictEqual(estimateHkAnnouncement({actions:[action(1,'1')],quantity:100,fxRows:[],receiptDate:'2026-09-30'}).reason,'missing_historical_dividend_fx');
const net={...action(4,'100'),cash_per_share_after_tax:'72',currency_code:'CNY',raw_payload:{...action(4,'100').raw_payload,taxTreatment:{kind:'HK_connect_personal',amountBasis:'net',layers:[]}}};
assert.strictEqual(estimateHkAnnouncement({actions:[net],quantity:1,receiptDate:'2026-09-30'}).amount,72,'公告明确税后净额不重扣');
const {hkDividendCalendar}=require('../services/cashIncome'),years=require('../config/holidays').loadHolidays().years;
const calendar=hkDividendCalendar(years,[]);
assert.strictEqual(hkReceiptDate('2026-09-08',calendar).receiptDate,'2026-09-11');
assert.strictEqual(hkReceiptDate('2026-09-30',calendar).receiptDate,'2026-10-12','国庆及周末顺延，不按自然日+3');
assert.strictEqual(hkReceiptDate('2026-08-14',calendar).receiptDate,'2026-08-19','派息早于导入基准但到账晚于基准');
assert.strictEqual(hkReceiptDate('2026-10-16',calendar).receiptDate,'2026-10-22','香港重阳休市顺延');
assert.strictEqual(hkReceiptDate('2026-12-31',calendar).reason,'missing_hk_dividend_calendar','未知下一年不猜开市');
assert.strictEqual(estimateHkAnnouncement({actions:[net],quantity:1}).reason,'missing_hk_dividend_calendar','不隐式回退T+0');
assert.strictEqual(M.isEffectiveFlow({flow_type:'dividend_tax',status:'estimated',quality_status:'authorized_deferred_tax_calculation',evidence:{authorizedPolicy:'cash-income-v1'}}),true);
assert.strictEqual(M.isEffectiveFlow({flow_type:'dividend_tax',status:'estimated',quality_status:'authorized_deferred_tax_calculation',evidence:{}}),false);
console.log('announcement cash income: personal tax isolation, ordinary/special components, historical FX, net no double tax and authorized deferred tax passed');
const {userTaxExemption,userScopeExclusion}=require('../services/cashIncome');
const exemption={eventKey:'event-a',code:'000001',confirmedBy:'owner',holdingPeriod:'over_one_year',allEntitledShares:true,quantity:1900};
const policy={cnDividendExemptions:[exemption],dividendScopeExclusions:[{code:'404002',confirmedBy:'owner',reason:'退市搜特转债不参与股票分红',outsideStockDividendScope:true}]};
const cnIdentity={market:'CN',code:'000001'},cnAction={currency_code:'CNY',raw_payload:{documentId:'official'}};
assert.deepStrictEqual(userTaxExemption(policy,'owner',cnIdentity,cnAction,'event-a',{quantity:1900}),exemption);
assert.strictEqual(userTaxExemption(policy,'other',cnIdentity,cnAction,'event-a',{quantity:1900}),null);
assert.strictEqual(userTaxExemption(policy,'owner',cnIdentity,cnAction,'different-event',{quantity:1900}),null);
assert.strictEqual(userTaxExemption(policy,'owner',cnIdentity,cnAction,'event-a',{quantity:2000}),null);
assert.strictEqual(userTaxExemption(policy,'owner',{...cnIdentity,market:'HK'},cnAction,'event-a',{quantity:1900}),null);
assert.strictEqual(userTaxExemption(policy,'owner',cnIdentity,{currency_code:'CNY'},'event-a',{quantity:1900}),null);
assert.strictEqual(userScopeExclusion(policy,'owner','404002').outsideStockDividendScope,true);
assert.strictEqual(userScopeExclusion(policy,'other','404002'),null);
assert.strictEqual(userScopeExclusion(policy,'owner','501312'),null);
