const assert=require('assert');
require('dotenv').config();delete process.env.DATABASE_URL;process.env.PGDATABASE=process.env.PGTESTDATABASE||'portfolio_test';
const {pool}=require('../db/connection');
const {validate,importActual}=require('../services/cashIncomeActual');
const {syncPending,changePending,keyOf}=require('../services/cashIncomePending');
const {loadAccountData}=require('../db/accounts');
const U='cash_actual_test',A='本账户',ID='cash_actual_test_id',key='repo:204001.SH:2026-09-02';
const record={eventKey:key,date:'2026-09-03',flow_type:'repo_interest',amountCny:'1.23',sourceRef:'fixture-voucher',settlement:{tax:{amount:'0.00',basis:'actual'}}};
async function cleanup(){await pool.query('DELETE FROM accounts WHERE username=$1',[U]);for(const t of ['cash_flows','nav_history','account_data'])await pool.query(`DELETE FROM ${t} WHERE username=$1`,[U]);await pool.query('DELETE FROM users WHERE username=$1',[U]);}
(async()=>{try{
  for(const r of [null,{...record,amountCny:1.23},{...record,amountCny:'-1'},{...record,date:'2026-02-30'},{...record,eventKey:'repo:204001.SH:bad'},{...record,currency:'HKD'},{...record,originalAmount:'2'},{...record,settledAt:'2026-09-02T23:00:00+08:00'}])assert.throws(()=>validate([r]));
  assert.throws(()=>validate([record,record]),/重复/);
  assert.strictEqual(validate([{...record,currency:'HKD',originalAmount:'1.40',settledAt:'2026-09-02T17:00:00Z'}])[0].currency,'HKD');
  await cleanup();await pool.query("INSERT INTO users(username,password,accounts,status,auth_version) VALUES($1,'x',$2,'active',1)",[U,JSON.stringify([A])]);
  await pool.query('INSERT INTO accounts(id,username,account_name,cash_base,hk_rate) VALUES($1,$2,$3,0,1)',[ID,U,A]);
  await pool.query("INSERT INTO account_data(username,account_name,data,version) VALUES($1,$2,'{}',0)",[U,A]);
  await pool.query(`INSERT INTO nav_history(username,account_name,account_id,date,nav,total_asset,invested,cash_cny,market_value_cny,system_market_value_at_snapshot,snapshot_source,is_locked,source_priority) VALUES($1,$2,$3,'2026-09-01',1,10000,10000,10000,0,0,'imported',true,100)`,[U,A,ID]);
  await pool.query(`INSERT INTO cash_flows(id,username,account_name,account_id,date,amount,flow_type,origin,status,event_key,anchor_date) VALUES('actual-test',$1,$2,$3,'2026-09-03',3,'repo_interest','system','estimated',$4,'2026-09-01')`,[U,A,ID,key]);
  assert.strictEqual((await importActual(U,A,[record],0)).changed,1);
  let d=await loadAccountData(U,A);assert.strictEqual(d.cash,10001.23);assert.strictEqual(d.authoritativeInvested,10000);
  assert.strictEqual((await importActual(U,A,[{...record,settlement:{tax:{basis:'actual',amount:'0.00'}}}],d.version)).changed,0,'嵌套键顺序不制造修订');
  assert.strictEqual((await importActual(U,A,[{...record,settlement:{tax:{amount:'0.01',basis:'actual'}}}],d.version)).changed,1,'嵌套证据变化必须产生修订');
  d=await loadAccountData(U,A);await assert.rejects(()=>importActual(U,A,[record],0),/版本|修改/);
  await assert.rejects(()=>importActual('other',A,[record],d.version),/不存在/);
  await assert.rejects(()=>importActual(U,A,[{...record,eventKey:'repo:204001.SH:2026-09-04'}],d.version),/不属于/);
  await importActual(U,A,[{...record,currency:'HKD',originalAmount:'1.40',settledAt:'2026-09-03T10:00:00+08:00'}],d.version);
  const saved=(await pool.query("SELECT currency,original_amount::text,settled_at FROM cash_flows WHERE id='actual-test'")).rows[0];assert.strictEqual(saved.currency,'HKD');assert.strictEqual(saved.original_amount,'1.400000');assert(saved.settled_at);
  d=await loadAccountData(U,A);await importActual(U,A,[{...record,status:'revoked'}],d.version);assert.strictEqual((await loadAccountData(U,A)).cash,10000);
  const pending={code:'204001.SH',eventKey:key,reason:'missing_repo_daily_rate'};
  await syncPending(pool,ID,[pending],1,U);await syncPending(pool,ID,[],2,U);
  assert.strictEqual((await pool.query('SELECT state FROM account_cash_income_pending WHERE account_id=$1',[ID])).rows[0].state,'pending','空结果不恢复');
  await syncPending(pool,ID,[],2,U,[{code:pending.code,eventKey:key,rawRecordId:123,reason:'verified_rate'}]);
  assert.strictEqual((await pool.query('SELECT state FROM account_cash_income_pending WHERE account_id=$1',[ID])).rows[0].state,'resolved');
  d=await loadAccountData(U,A);await changePending(U,A,keyOf(pending),{exclude:true,reason:'用户测试排除',version:d.version});
  await syncPending(pool,ID,[pending],3,U);assert.strictEqual((await pool.query('SELECT state FROM account_cash_income_pending WHERE account_id=$1',[ID])).rows[0].state,'excluded_by_user');
  const hk=(await pool.query("SELECT instrument_id,canonical_code FROM core.instruments WHERE market='HK' AND asset_class='stock' LIMIT 1")).rows[0];assert(hk);
  const hkEvent='dividend:'+hk.instrument_id+':2026-09-01:2026-09-02';
  await syncPending(pool,ID,[{code:hk.canonical_code,eventKey:hkEvent,reason:'missing_stock_connect_net_cny_settlement'}],4,U);
  const hkActual={eventKey:hkEvent,date:'2026-09-08',flow_type:'dividend',currency:'HKD',originalAmount:'72.00',amountCny:'64.80',sourceRef:'fixture-HK-net-voucher',settlement:{amountBasis:'net'}};
  d=await loadAccountData(U,A);await assert.rejects(()=>importActual(U,A,[{...hkActual,settlement:{}}],d.version),/港股实收必须明确/);
  await importActual(U,A,[hkActual],d.version);assert.strictEqual((await loadAccountData(U,A)).cash,10064.8,'人民币实收优先，不重复按20%扣税');
  d=await loadAccountData(U,A);assert.strictEqual((await importActual(U,A,[hkActual],d.version)).changed,0);
  const taxEvent=require('../services/cashDividendSettlement').taxEvent('dividend:1:2026-09-01:2026-09-02','sale-fixture');
  await syncPending(pool,ID,[{code:'600000',eventKey:taxEvent,reason:'deferred_tax_actual_deduction_pending',notBefore:'2026-09-08',expectedTax:'1.23'}],5,U);
  const taxActual={eventKey:taxEvent,date:'2026-09-08',flow_type:'dividend_tax',amountCny:'-1.23',sourceRef:'fixture-tax-deduction'};
  await assert.rejects(()=>importActual(U,A,[{...taxActual,date:'2026-09-07'}],d.version),/不能早于/);
  await importActual(U,A,[taxActual],d.version);assert.strictEqual((await loadAccountData(U,A)).cash,10063.57);
  d=await loadAccountData(U,A);await importActual(U,A,[{...taxActual,amountCny:'-1.00'}],d.version);assert.strictEqual((await loadAccountData(U,A)).cash,10063.8,'逐卖出事件更正不叠加扣税');
  console.log('cash income actual: ownership, precision, replacement, nested idempotence, revocation and evidence recovery passed');
}finally{await cleanup();await pool.end();}})().catch(e=>{console.error(e);process.exitCode=1;});
