// 聚合所有子模块，对外导出与原 server/db.js 完全一致的接口（调用方无需改动）
const connection = require('./connection');
const util = require('./util');
const migrations = require('./migrations');
const users = require('./users');
const accounts = require('./accounts');
const brokers = require('./brokers');
const jobs = require('./jobs');
const config = require('./config');

module.exports = {
  pool: connection.pool,
  initSchema: migrations.initSchema,
  runMigrations: migrations.runMigrations,
  migrateFromJson: migrations.migrateFromJson,
  migrateToStructured: migrations.migrateToStructured,
  migrateAccountsTable: accounts.migrateAccountsTable,
  getAccountMeta: accounts.getAccountMeta,
  syncUserAccounts: brokers.syncUserAccounts,
  loadBrokers: brokers.loadBrokers,
  isValidBroker: brokers.isValidBroker,
  getAccountBrokers: brokers.getAccountBrokers,
  updateAccountBroker: brokers.updateAccountBroker,
  loadUsers: users.loadUsers,
  loadUser: users.loadUser,
  registerUser: users.registerUser,
  updateUserAccounts: users.updateUserAccounts,
  hashPwd: util.hashPwd,
  verifyPwd: util.verifyPwd,
  getUserProfile: users.getUserProfile,
  getUserAuth: users.getUserAuth,
  countUsers: users.countUsers,
  listUsers: users.listUsers,
  setUserRole: users.setUserRole,
  setUserStatus: users.setUserStatus,
  adminSetPassword: users.adminSetPassword,
  deleteUser: users.deleteUser,
  getUserDetail: users.getUserDetail,
  updateUserProfile: users.updateUserProfile,
  changePassword: users.changePassword,
  updateLastLogin: users.updateLastLogin,
  ensureAdmin: users.ensureAdmin,
  adminOverview: jobs.adminOverview,
  adminJobRuns: jobs.adminJobRuns,
  adminListBrokers: brokers.adminListBrokers,
  createBroker: brokers.createBroker,
  updateBroker: brokers.updateBroker,
  deleteBroker: brokers.deleteBroker,
  getConfig: config.getConfig,
  setConfig: config.setConfig,
  listAnnouncements: config.listAnnouncements,
  createAnnouncement: config.createAnnouncement,
  updateAnnouncement: config.updateAnnouncement,
  deleteAnnouncement: config.deleteAnnouncement,
  getChangelog: config.getChangelog,
  addChangelogItem: config.addChangelogItem,
  auditLog: config.auditLog,
  listAudit: config.listAudit,
  loadAccountData: accounts.loadAccountData,
  saveAccountData: accounts.saveAccountData,
  saveDailyPrices: accounts.saveDailyPrices,
  loadDailyPrices: accounts.loadDailyPrices,
  upsertNav: accounts.upsertNav,
  upsertIndexPoints: accounts.upsertIndexPoints,
  loadIndexPoints: accounts.loadIndexPoints,
  tryClaimJob: jobs.tryClaimJob,
  releaseJob: jobs.releaseJob,
  startJobRun: jobs.startJobRun,
  finishJobRun: jobs.finishJobRun,
  uid: util.uid,
  DATA_DIR: connection.DATA_DIR,
};
